export const routes = {
  login: '/login',
  index: '/index',
  clients: '/clients',
  centers: '/centers',
  services: '/services',
  specialists: '/specialists',
  appointment: '/appointment',
  users: '/users',
  myAccount: '/my-account',
  clientHome: '/client',
  clientAppointments: '/client/appointments',
  clientBook: '/client/book',
  clientProfile: '/client/profile',
} as const;
